services:
  webserver:
    build: ./webserver
    container_name: webserver
    ports:
      - "8098:8000"

  client:
    build: ./client
    container_name: client
    depends_on:
      - webserver

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
